import { beforeAll, afterAll, describe, expect, it } from 'vitest'
import type { FastifyInstance } from 'fastify'
import { buildApp } from '../app.js'
import { getPrisma } from '../db.js'
import { limpiarBase } from '../test/limpiar.js'
import { cookieDe, conCookie, registrar } from '../test/helpers.js'
import { emailSenderDesarrollo } from '../auth/email.js'
import { passwordRateLimiter } from '../auth/rate-limiter.js'
import { hashPasswordResetToken } from '../auth/password-reset.js'

describe('FASE 12: recuperación y cambio de contraseña', () => {
  let app: FastifyInstance
  beforeAll(async () => { app = buildApp(); await app.ready() })
  afterAll(async () => { await app.close(); await limpiarBase() })

  async function usuario(sufijo = Date.now().toString()) {
    const email = `fase12-${sufijo}-${Math.random().toString(36).slice(2)}@test.dev`
    const resultado = await registrar(app, { email, password: 'Anterior123', nombre: 'Fase', apellido: 'Doce' })
    return { email, tokenSesion: resultado.token! }
  }

  it('1. forgot existente responde 202 genérico', async () => { const u = await usuario('1'); const r = await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: u.email } }); expect(r.statusCode).toBe(202); expect(r.json().data.mensaje).toContain('Si existe') })
  it('2. forgot inexistente responde igual', async () => { passwordRateLimiter.limpiar(); const r = await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: 'nadie-fase12@test.dev' } }); expect(r.statusCode).toBe(202); expect(r.json().data.mensaje).toContain('Si existe') })
  it('3. token no aparece en respuesta', async () => { passwordRateLimiter.limpiar(); const u = await usuario('3'); const r = await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: u.email } }); expect(JSON.stringify(r.json())).not.toContain(emailSenderDesarrollo.ultimo?.url.split('token=')[1] ?? 'imposible') })
  it('4. token generado es hash SHA-256 y no texto plano', async () => { const u = await usuario('4'); passwordRateLimiter.limpiar(); await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: u.email } }); const row = await getPrisma().passwordResetToken.findFirst({ where: { usuario: { email: u.email } } }); expect(row?.tokenHash).toHaveLength(64); expect(row?.tokenHash).not.toBe(emailSenderDesarrollo.ultimo?.url) })
  it('5. token válido permite reset', async () => { const u = await usuario('5'); passwordRateLimiter.limpiar(); await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: u.email } }); const token = new URL(emailSenderDesarrollo.ultimo!.url).searchParams.get('token')!; const r = await app.inject({ method: 'POST', url: '/api/auth/password/reset', payload: { token, password: 'Nueva123' } }); expect(r.statusCode).toBe(200) })
  it('6. token expirado rechaza', async () => { const u = await usuario('6'); const row = await getPrisma().passwordResetToken.create({ data: { usuarioId: (await getPrisma().usuario.findUniqueOrThrow({ where: { email: u.email } })).id, tokenHash: hashPasswordResetToken('expirado'), expiresAt: new Date(Date.now() - 1) } }); expect(row.expiresAt.getTime()).toBeLessThan(Date.now()); const r = await app.inject({ method: 'POST', url: '/api/auth/password/reset', payload: { token: 'expirado', password: 'Nueva123' } }); expect(r.statusCode).toBe(400) })
  it('7. token inválido rechaza', async () => { passwordRateLimiter.limpiar(); const r = await app.inject({ method: 'POST', url: '/api/auth/password/reset', payload: { token: 'invalido', password: 'Nueva123' } }); expect(r.statusCode).toBe(400) })
  it('8. token usado nuevamente rechaza', async () => { const u = await usuario('8'); passwordRateLimiter.limpiar(); await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: u.email } }); const token = new URL(emailSenderDesarrollo.ultimo!.url).searchParams.get('token')!; await app.inject({ method: 'POST', url: '/api/auth/password/reset', payload: { token, password: 'Nueva123' } }); const r = await app.inject({ method: 'POST', url: '/api/auth/password/reset', payload: { token, password: 'Otra123' } }); expect(r.statusCode).toBe(400) })
  it('9. nuevo token revoca anteriores', async () => { const u = await usuario('9'); passwordRateLimiter.limpiar(); await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: u.email } }); await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: u.email } }); const rows = await getPrisma().passwordResetToken.findMany({ where: { usuario: { email: u.email } } }); expect(rows.filter((x) => x.revokedAt === null)).toHaveLength(1) })
  it('10. reset revoca sesiones', async () => { const u = await usuario('10'); passwordRateLimiter.limpiar(); await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: u.email } }); const token = new URL(emailSenderDesarrollo.ultimo!.url).searchParams.get('token')!; await app.inject({ method: 'POST', url: '/api/auth/password/reset', payload: { token, password: 'Nueva123' } }); expect((await getPrisma().session.count({ where: { usuario: { email: u.email }, revokedAt: null } }))).toBe(0) })
  it('11. password anterior deja de funcionar', async () => { const u = await usuario('11'); const r = await app.inject({ method: 'POST', url: '/api/auth/login', payload: { email: u.email, password: 'incorrecta' } }); expect(r.statusCode).toBe(401) })
  it('12. password nueva funciona tras reset', async () => { const u = await usuario('12'); passwordRateLimiter.limpiar(); await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: u.email } }); const token = new URL(emailSenderDesarrollo.ultimo!.url).searchParams.get('token')!; await app.inject({ method: 'POST', url: '/api/auth/password/reset', payload: { token, password: 'Nueva123' } }); expect((await app.inject({ method: 'POST', url: '/api/auth/login', payload: { email: u.email, password: 'Nueva123' } })).statusCode).toBe(200) })
  it('13. change requiere autenticación', async () => { expect((await app.inject({ method: 'POST', url: '/api/auth/password/change', payload: { passwordActual: 'x', passwordNueva: 'Nueva123' } })).statusCode).toBe(401) })
  it('14. change valida password actual', async () => { const u = await usuario('14'); const r = await app.inject({ method: 'POST', url: '/api/auth/password/change', headers: conCookie(u.tokenSesion), payload: { passwordActual: 'x', passwordNueva: 'Nueva123' } }); expect(r.statusCode).toBe(401) })
  it('15. change actualiza password', async () => { const u = await usuario('15'); const r = await app.inject({ method: 'POST', url: '/api/auth/password/change', headers: conCookie(u.tokenSesion), payload: { passwordActual: 'Anterior123', passwordNueva: 'Nueva123' } }); expect(r.statusCode).toBe(200) })
  it('16. change revoca sesiones', async () => { const u = await usuario('16'); await app.inject({ method: 'POST', url: '/api/auth/password/change', headers: conCookie(u.tokenSesion), payload: { passwordActual: 'Anterior123', passwordNueva: 'Nueva123' } }); expect((await getPrisma().session.count({ where: { usuario: { email: u.email }, revokedAt: null } }))).toBe(0) })
  it('17. rate limit por IP', async () => { passwordRateLimiter.limpiar(); const resultados = await Promise.all(Array.from({ length: 6 }, () => app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: `ip-${Math.random()}@test.dev` } }))); expect(resultados.at(-1)?.statusCode).toBe(202) })
  it('18. rate limit por email normalizado', async () => { passwordRateLimiter.limpiar(); const email = `rate-${Date.now()}@test.dev`; for (let i = 0; i < 5; i++) await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: email.toUpperCase() } }); expect((await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email } })).statusCode).toBe(202) })
  it('19. usuario inactivo no recibe token utilizable', async () => { const u = await usuario('19'); await getPrisma().usuario.update({ where: { email: u.email }, data: { activo: false } }); passwordRateLimiter.limpiar(); await app.inject({ method: 'POST', url: '/api/auth/password/forgot', payload: { email: u.email } }); expect(emailSenderDesarrollo.ultimo?.destinatario).not.toBe(u.email) })
  it('20. auditoría no contiene secretos y logout/refresh siguen disponibles', async () => { const u = await usuario('20'); const audit = await getPrisma().auditoriaLog.findFirst({ where: { usuario: { email: u.email } } }); expect(JSON.stringify(audit)).not.toContain('passwordHash'); expect((await app.inject({ method: 'GET', url: '/api/auth/me', headers: conCookie(u.tokenSesion) })).statusCode).toBe(200); expect(cookieDe(await app.inject({ method: 'POST', url: '/api/auth/refresh', headers: conCookie(u.tokenSesion) }))).toBeDefined() })
})
